
name: 'Setup Node and Install Dependencies'
description: 'Set up Node.js and install dependencies for React frontend'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.8'
    - name: Install dependencies
      run: npm install
      shell: bash