version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cloudvalet
      POSTGRES_PASSWORD: cloudvaletpass
      POSTGRES_DB: cloudvaletdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://cloudvalet:cloudvaletpass@db:5432/cloudvaletdb
volumes:
  postgres_data:
