name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: cloudvalet
          POSTGRES_PASSWORD: cloudvaletpass
          POSTGRES_DB: cloudvaletdb
        ports:
          - 55432:5432
        options: >-
          --health-cmd="pg_isready -U cloudvalet"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python and Install Requirements
        uses: ./.github/actions/setup-python-action
        with:
          working-directory: Cloud-Valet/app
      - name: Start FastAPI server and run backend tests
        env:
          DATABASE_URL: postgresql+asyncpg://cloudvalet:cloudvaletpass@localhost:55432/cloudvaletdb
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 --reload &
          for i in {1..20}; do
            curl -s http://127.0.0.1:8000/ && break
            sleep 1
          done
          pytest
        working-directory: Cloud-Valet/app

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node dependencies
        run: npm install
        working-directory: cloud-valet-frontend
      - name: Run frontend tests
        run: npm test -- --watchAll=false
        working-directory: cloud-valet-frontend
